redealumni/slate

- source/index.html.md
> Application docs

- source/index.html.md
> Adds admission info

- source/index.html.md
> update base notify and base new-application notify

- source/index.html.md
> fixes course_sku in admissions object info

- source/index.html.md
> Fixes some admission attributes descriptions

- source/index.html.md
> Adds exam info (WIP)

- source/index.html.md
> Adds exam info

- source/index.html.md
> adds exam addition and exam reactivation

- source/index.html.md
- source/stylesheets/_variables.scss
> fix change

- source/index.html.md
> fixes some request commands

- source/index.html.md
> updates after validations [WIP]

- source/index.html.md
> adds enem exam info

- source/index.html.md
> fixes enem exam info

- source/index.html.md
> adds response for objects created by a json file and fixes some requests

- source/beta.html.md
- source/index.html.md
https://app.asana.com/0/269025395529904/527383519029274
* Adds description to each error message
* Message errors in english
* Puts "type" attributes in a more intuitive spot
> Updates and fixes documentation

- source/beta.html.md
- source/index.html.md
[Asana link](https://app.asana.com/0/292641971923670/531610653429612)
* Adds pagination info to documentation
* Adds reference to pagination section to each block that uses cursors
* Removes `next_page` and `previous_page` attributes, adds `has_more` instead
> Adds pagination info

- source/beta.html.md
- source/index.html.md
[Task do asana](https://app.asana.com/0/292641971923670/539000188532014)
> Adds start_date/end_date parameters to pagination

- source/beta.html.md
- source/index.html.md
Atualizado todas as formatações de data para ISO8601
Exemplo:
"2018-02-09T02:01:44Z"
> fix date formatting

- source/beta.html.md
- source/index.html.md
https://app.asana.com/0/292641971923670/589949753974505
Obs: Só mudei para a API de notificação de nova admissão, para modificar para o restante da API, tem outra task: https://app.asana.com/0/292641971923673/608372517899993
> 589949753974505 adds discount percentage to new admission notifications

- source/beta.html.md
- source/index.html.md
https://app.asana.com/0/292641971923670/615346345491380
Atualizado para ter novo objeto **course**, contendo id e o desconto que o aluno adquiriu.
> change from course-sku to course

- source/queropago.html.md
- Alterado os eventos para ficarem de acordo com a API
> Update events to be equal to API

- source/queropago.html.md
Edita endpoins já criados, e adiciona os novos
> Add Student, Course, Campus, City and State endpoints

- Gemfile
- Gemfile.lock
- config.rb
- source/index.html.md
Tarefa:
https://app.asana.com/0/292641971923670/1121057501943235/f
Alterações:
- Atualiza exemplos de retorno
- Remove referencias ao step do admissions
> update examples return

- source/admissao.html.md
- source/beta.html.md
- source/index.html.md
https://quero.atlassian.net/secure/RapidBoard.jspa?rapidView=108&modal=detail&selectedIssue=AD-102
> Add address complement to API

- source/queropago.html.md
> Add debt agreement requests and event

- source/index.html.md
- Adiciona documentação para evento de notificação de matrícula automática
> AD-494: Adiciona evento de notificação para matrícula automática

- source/admissao.html.md
Adiciona **Notificar universidade sobre aluno pronto para matrícula** na documentação da API de admissões.
> Add admission.auto-enroll to admissions.md

- source/queropago.html.md
> Update qp enrollment
